version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-patch-minor:
        update-types: ["patch", "minor"]
      actions-major:
        update-types: ["major"]
    commit-message:
      prefix: "ci"
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      bundler-patch-minor:
        update-types: ["patch", "minor"]
      bundler-major:
        update-types: ["major"]
    commit-message:
      prefix: "chore"
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      swift-patch-minor:
        update-types: ["patch", "minor"]
      swift-major:
        update-types: ["major"]
    commit-message:
      prefix: "chore"
